apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - access-entries/ks.yaml
#  - access-entries/ocirepo.yaml
  - appli-oci/ks.yaml
  - appli-oci/ocirepo.yaml
#  - aws-lb-controller/ks.yaml
#  - aws-lb-controller/ocirepo.yaml
  - cert-manager/ks.yaml
  - cert-manager/ocirepo.yaml
  - external-secrets/ks.yaml
  - external-secrets/ocirepo.yaml
#  - istio/ks.yaml
#  - istio/ocirepo.yaml
#  - karpenter/ks.yaml
#  - karpenter/ocirepo.yaml
#  - splunk-uf/ks.yaml
#  - splunk-uf/ocirepo.yaml
#  - twistlock-defender/ks.yaml
#  - twistlock-defender/ocirepo.yaml
