name: PR_Pipeline

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  call-reusable-workflow-ci:
    uses: a14T2n6g2l59Hgnsmb1Sc4L6CCY7U9XI2cmTor8/cloudhandson-eks-reusable-workflow/.github/workflows/reusable-workflow-tooling.yaml@workflow_test
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
